### PR TITLE
indexes badge metadata updates

### PR DESCRIPTION
**Pull request by elmariachi111**
- updates contract abis (built contract repo with foundry)
- adds Badge.uri / uriUpdatedAt fields
- updates handler defs for metadata
- adds handler for metadata uri updates
- fixes Raft metadata update handler

test-deployed at https://thegraph.com/hosted-service/subgraph/elmariachi111/otter-metadata for görli

~~this doesn't decode strings on  `MetadataUpdated` event correctly~~
Note that you cannot read strings easily on a subgraph handler from an `indexed string` event log parameter. I'm falling back to calling the contract here (as you do on the Raft contract already)

### CODE REVIEW

**Comment by rahulrumalla** [comment]
Hello @elmariachi111 thank you for the PR 🙏🏽 I spent some time going through it and had a couple of high-level design comments. It is a tricky one, so bear with me. 

Some high-level points for consideration
- The `BadgeSpec` is where all the uri and metadata of a badge is held and is considered to the source of truth. So all changes should be reflected in this entity. 
- Because the BadgeSpec's entity ID is essentialy the CID, updating the metadata would mean it would be using a new CID. I think this is where it gets tricky. Since if we were to update the original BadgeSpec entity, it would have the old CID but the metadata from the new CID. And I think this would cause a whole bunch of dowstream problems
- There is also the problem that you highlighted where indexed string data is not accessible withing the event handler in the subgraph

I suggest the following design. I am not sure yet if there are further unknowns. Do you see any 
- When a BadgeSpec's metadata is updated i.e., when `MetadataUpdate` is emitted on a badge, we create a "new" BadgeSpec entity using the new CID. 
- We could copy over the values from the old BadgeSpec using the old CID to the new BadgeSpec using the new CID. The code from `handleSpecCreated` can be refactored in order to reuse that internally across different event handlers
- For the above, we can essentially use `badge.spec` to fetch the current/old entity and then use `badgeContract.tokenUri` to fetch the new uri & CID to create the new entity
- Once the new BadgeSpec entity is created, we delete the old BadgeSpec entity

Operational suggestions
- I changed the base branch to dev so that the CI will deploy to all testnets upon merge
- You need to bump up the version label for Sepolia deployment in package.json in order to trigger the deployment of the new version

I'm happy to take this over if you like. But if you prefer to continue working on this per my comments above that is totally fine as well, especially since you already started :) Lmk what you prefer.

**Comment by rahulrumalla** [comment]
A bit more detail on the CID issue I mentioned above

If you query using this on the subgraph you deployed to
```graphql
{
  badges(
    first: 10, orderBy: uriUpdatedAt, orderDirection: desc
    where: {
      uriUpdatedAt_not: null
    }
  ) {
    id
    uri
    uriUpdatedAt
    spec {
      id
      uri
      specUri
      metadata {
        name
      }
    }
  }
}
```

Here you can see that the badge uri and spec entity in it's reference's uri are different. So using the new CID, we won't be able to fetch the Spec entity since it is not yet indexed and also the metadata under it. 

```json
{
  "data": {
    "badges": [
      {
        "id": "badges:89510751899869881527945544944270747676875828014751488548037395633615016223503",
        "uri": "ipfs://bafyreihe5we6wplplodykmsbawry44xjgqrlaqxhzq2m6nis6xfmgdpuvnk/metadata.json",
        "uriUpdatedAt": 1691137440,
        "spec": {
          "id": "bafyreihe5we6wmplodykmsbawry44xjgqrlaqxhzq2m6nis6xfmgdpuvoe",
          "uri": "ipfs://bafyreihe5we6wmplodykmsbawry44xjgqrlaqxhzq2m6nis6xfmgdpuvoe/metadata.json",
          "specUri": "ipfs://bafyreihe5we6wmplodykmsbawry44xjgqrlaqxhzq2m6nis6xfmgdpuvoe/metadata.json",
          "metadata": {
            "name": "Bio.xyz"
          }
        }
      }
    ]
  }
}
```

**Comment by elmariachi111** [comment]
gm, I'm absolutey aware of that :) But you can still use the spec's `specUri` to find the badges "original" `BadgeSpec`. I'm not too familiar with the otterspace system design, so I'm happy to follow anything you think works best. 

Our requirement behind that change is rather simple: We'd like to attach "arbitrary" metadata to *unique* badges that all share the same purpose: identify the kyc/aml check state of an user. That's why I used the new `Badges:updateTokenURI` that updates the unique uri of a badge, to update a badge's custom metadata properties. Think of the badge being speced as "This user went to a kyc flow" and its unique properties being  [] identified [] aml list checked [] onchain aml good (oc without containing any PII data).

If I understood the architecture correctly, specs are an entity that reasons about a "kind of" badges (live example https://optimistic.etherscan.io/tx/0x87cbf189c4d6b2b3c005ce09135f2a1ab4841843b8a3ceb937df202ba4328a06 / https://ipfs.io/ipfs/bafyreicoihtrc6eaoolz3n5icitchitzig3r7ppv5k2e6zy6cu27bh7lpy/metadata.json) that refer to a common "raft" (aka community?) token id. But still, each *badge* in that "collection" (identified by a unique badge id, computed by the badge's initial mint parameters) bears an unique url that identifies its content and that *can* be customized by updating its intrinsic `tokenURIs` entry. That's how it's supposed to work on the contract imo.

So, imo we can't drop / update the full `BadgeSpec` since that would update the spec for all token bearers. If we were to "copy" a spec we'd end up with a lot of different badges that wouldn't be too easy to query from a single base spec ("show me the badges of this address that are kyc badges so I can fetch and verify its payload afterwards")

**Comment by elmariachi111** [comment]
sure.

So, imo a plain badge (that represents a user who identified them using a plain address) that we *could* issue in the beginning *can* resemble a very plain spec like the ones that are already issued (eg https://ipfs.io/ipfs/bafyreiazgva4qmiuqhyricahxoci3ixcbsb6hjegjgmzysmjhls3me6jcu/metadata.json). 

We'd like to extend it with custom props, like

```json
...
properties: {
...
  verification: {
    kyc: true,
    aml1: true,
    wl: false 
  }
}
...
```

which resembles our kyc / user verification process (there are 4 apis we use for this overall). The final structure of this one is still under discussion but it'd look somewhat like this.

Ideally that structure is partly already storable during a mint. The approach that one of my colleagues tries right now is
- airdrop a generic badge with our raft token using your `/api/external/badge/`{spec}`/airdrop` endpoint. under the hood this creates a plain badge that matches your spec-schema. 
- then she gets *that* metadata (eg by querying the contract / subgraph)
- then she leads the user thru the first kyc process & updates the issued badge (by id) with 1 new property
- then she continues with other processes

That's oc not efficient and costs quite some gas. What I'd rather suggest is:
- there's a plain badge spec that potentially but not necessarily contains an empty key for the verifications (`verification: {}`)
- we're staring the user's kyc process and once he achieves the first step we airdrop an initial badge with the first verification
- we're sequentially call other APIs and update the badge at once.

In the end all 4 kyc checks could be anchored during the initial airdrop, so there might not even be any need for the update, but there's a caveat:

Not each KYC step is mandatory to pass for the user to continue the real action. This actually depends on how much *value* they'd like to contribute. Some verification steps are only reqired once they want to contribute a certain amount to the protocol. There can (and likely will) be a situation where a user first starts contributing a low amount (only little kyc required) and then places another commitment with a higher amount some days later. In that case we might run the needed verification step and anchor that one by updating the token uri.

hth

**Comment by rahulrumalla** [comment]
Gotcha. Thank you for the detailed explanation @elmariachi111 I appreciate it

Could you change the following field names on badge, please? 
- `tokenUri`
- `tokenUriLastUpdatedAt` 

I can merge this right after and get you unblocked.

**Comment by rahulrumalla** [comment]
Another idea that comes to mind is that if you're creating a spec directly from the contract, you could extend this schema with yours and reference this in the spec and badge's metadata, if you hadn't considered that already.  

https://api.otterspace.xyz/schemas/badge/1.0.1.json

While there are no active plans yet, I wanted to use these schemas to help validate metadata.

**Comment by elmariachi111** [comment]
updated the prop names. currently deploying on https://api.thegraph.com/subgraphs/name/elmariachi111/otter-metadata.

I absolutely favor schematized metadata. We're actually using a quite similar approach to restrict IPNFT mints to only valid metadata: https://docs.molecule.to/documentation/ip-nfts/technical-components-of-ip-nfts/technical-details-for-developers#verify-and-sign-off-final-metadata. Here actually the protocol is still somewhat permissioned: everyone who wants to mint an IPNFT with custom metadata must have it signed off by a service that we're operating. It verifies integrity and conformance of the metadata (adding an explicit content check to it atm) and signs a message that's verified by the mint function. Thus we can guarantee (as long as that service is up) that only valid metadata goes on chain. 

So, I'm still wondering what would be the best approach for us now. I discussed this quite a bit with @nour-karoui and we'd particularly be interested in minting the "happy path" that simply attaches additional metadata on a badge. Imo we'll: 

- create a general spec for our badges with the "basic" metadata (description & image & empty custom props that will take values after the kyc process) like here https://docs.otterspace.xyz/documentation/contracts/create-a-badge-spec. That spec's ipfs cid becomes the spec's "id" on the subgraph
- airdrop a badge by using the spec uri that doesn't contain any custom values on the metadata (we now know that the user *intended* to become kyced :) 
- do our kyc thing. Which takes some minutes.
- call `updateTokenURI`on that tokenId with `_oldTokenUri` being the "original" spec id & `_newTokenUri` being the customized metadata.
- the badge's original spec uri needed for that step can always be recovered by the subgraph relation between badge & spec

Only open question from our side: would you recommend to do the original airdrop using the API or on chain directly? Also, this process doesn't obviously feel too right with regards to the otterspace original idea (a badge represents a membership, and that's it). Are you fine with us reinterpreting it this way (all badges are equal but some badges are more equal than others ;) )?

**Comment by rahulrumalla** [comment]
The above listed steps seem OK to me. 

--

> Only open question from our side: would you recommend to do the original airdrop using the API or on chain directly?

Use API or the app for gasless airdrops, after you enable it on the setting. Use contracts directly if you plan to pay for it yourself. Just make sure the caller address is an admin of the raft. 

>  Also, this process doesn't obviously feel too right with regards to the otterspace original idea (a badge represents a membership, and that's it). Are you fine with us reinterpreting it this way (all badges are equal but some badges are more equal than others ;) )?

I think this is totally fine. A Badge represents reputation within a network and reputation changes over time. This is quite in-line what we've anticipated. Excited to see dynamic reputation in practice :)

**Pull request merged**
