### PR TITLE
DEV-553: Added setTokenUri call to indexer

### PR DESCRIPTION
**Pull request by rahulrumalla**
Added setTokenUri function call to Raft contract to subscribe to tokenURI changes. 
Upon setting a new uri, I'm also updating the metadata from the new uri.

### CODE REVIEW

**Review by dsh-otter — APPROVED** [review]
dont quite understand what this function does or why would we call it, but looks ok

**Comment by rahulrumalla** [comment]
> dont quite understand what this function does or why would we call it, but looks ok

so we are calling setTokenURI, a function on our contracts, when we update the raftToken's URI. What's happening now is that when we call this func and update the uri, the data that is already indexed in subgragh was not updated. This patch subscribed to those and makes sure our subgraph is also updated.

This stemmed from the bug we saw with TE.

**Comment by dsh-otter** [comment]
> > dont quite understand what this function does or why would we call it, but looks ok
> 
> so we are calling setTokenURI, a function on our contracts, when we update the raftToken's URI. What's happening now is that when we call this func and update the uri, the data that is already indexed in subgragh was not updated. This patch subscribes to those changes and makes sure our subgraph is also updated.
> 
> This stemmed from the bug we saw with TE.

I see, thank you for the explanation. But why would you update the tokenUri? isnt it immutable?

**Comment by rahulrumalla** [comment]
> > > dont quite understand what this function does or why would we call it, but looks ok
> > 
> > 
> > so we are calling setTokenURI, a function on our contracts, when we update the raftToken's URI. What's happening now is that when we call this func and update the uri, the data that is already indexed in subgragh was not updated. This patch subscribes to those changes and makes sure our subgraph is also updated.
> > This stemmed from the bug we saw with TE.
> 
> I see, thank you for the explanation. But why would you update the tokenUri? isnt it immutable?

For badges they are immutable, but for Raft the uri is updatable. The storage in contracts can be manipulated if we provide that functionality.

**Pull request merged**
